return { 
  tree_views = { 
    { 
      { 
        width = 400, 
        height = 400, 
        x = 0, 
        y = 0, 
        children = { 
          { 
            width = 400, 
            height = 17, 
            x = 0, 
            y = 0, 
            parent = '<cycle_ref:4>', 
            children = { 
            }, 
            name = "table: 0x027a2d1093d0", 
            textColor = { 
              0, 
              0, 
              0, 
              1, 
            }, 
            hoverColor = { 
              0.8, 
              0.8, 
              1, 
              1, 
            }, 
            item_height = 30, 
            backgroundColor = { 
              0.75, 
              0.75, 
              0.75, 
              1, 
            }, 
            items = { 
              { 
                width = 32, 
                height = 17, 
                x = 0, 
                y = 0, 
                name = "文件", 
                items = { 
                  { 
                    width = 100, 
                    height = 30, 
                    x = 0, 
                    y = 17, 
                    name = "新建2", 
                    items = { 
                      { 
                        serial_number = 1, 
                        width = 100, 
                        height = 30, 
                        x = 100, 
                        y = 32, 
                        layer = 3, 
                        is_unfold = false, 
                        name = "新建3", 
                      }, 
                      { 
                        serial_number = 2, 
                        width = 100, 
                        height = 30, 
                        x = 100, 
                        y = 62, 
                        layer = 3, 
                        is_unfold = false, 
                        name = "另存3", 
                      }, 
                      { 
                        serial_number = 3, 
                        width = 100, 
                        height = 30, 
                        x = 100, 
                        y = 92, 
                        layer = 3, 
                        is_unfold = false, 
                        name = "退出3", 
                      }, 
                      width = 100, 
                      height = 90, 
                      x = 100, 
                      count = 3, 
                      y = 32, 
                    }, 
                    layer = 2, 
                    is_unfold = false, 
                    serial_number = 1, 
                  }, 
                  { 
                    width = 100, 
                    height = 30, 
                    x = 0, 
                    y = 47, 
                    name = "另存2", 
                    items = { 
                      { 
                        serial_number = 1, 
                        width = 100, 
                        height = 30, 
                        x = 100, 
                        y = 62, 
                        layer = 3, 
                        is_unfold = false, 
                        name = "新建3", 
                      }, 
                      { 
                        serial_number = 2, 
                        width = 100, 
                        height = 30, 
                        x = 100, 
                        y = 92, 
                        layer = 3, 
                        is_unfold = false, 
                        name = "另存3", 
                      }, 
                      { 
                        serial_number = 3, 
                        width = 100, 
                        height = 30, 
                        x = 100, 
                        y = 122, 
                        layer = 3, 
                        is_unfold = false, 
                        name = "退出3", 
                      }, 
                      width = 100, 
                      height = 90, 
                      x = 100, 
                      count = 3, 
                      y = 62, 
                    }, 
                    layer = 2, 
                    is_unfold = false, 
                    serial_number = 2, 
                  }, 
                  { 
                    serial_number = 3, 
                    width = 100, 
                    height = 30, 
                    x = 0, 
                    y = 77, 
                    layer = 2, 
                    is_unfold = false, 
                    name = "退出2", 
                  }, 
                  width = 100, 
                  height = 90, 
                  x = 0, 
                  count = 3, 
                  y = 17, 
                }, 
                layer = 1, 
                is_unfold = false, 
                serial_number = 1, 
              }, 
              { 
                width = 38, 
                height = 17, 
                x = 32, 
                y = 0, 
                name = "视图1", 
                items = { 
                  { 
                    serial_number = 1, 
                    width = 100, 
                    height = 30, 
                    x = 32, 
                    y = 17, 
                    layer = 2, 
                    is_unfold = false, 
                    name = "新建2", 
                  }, 
                  { 
                    serial_number = 2, 
                    width = 100, 
                    height = 30, 
                    x = 32, 
                    y = 47, 
                    layer = 2, 
                    is_unfold = false, 
                    name = "另存2", 
                  }, 
                  { 
                    serial_number = 3, 
                    width = 100, 
                    height = 30, 
                    x = 32, 
                    y = 77, 
                    layer = 2, 
                    is_unfold = false, 
                    name = "退出2", 
                  }, 
                  width = 100, 
                  height = 90, 
                  x = 32, 
                  count = 3, 
                  y = 17, 
                }, 
                layer = 1, 
                is_unfold = false, 
                serial_number = 2, 
              }, 
              { 
                serial_number = 3, 
                width = 32, 
                height = 17, 
                x = 70, 
                y = 0, 
                layer = 1, 
                is_unfold = false, 
                name = "查看", 
              }, 
              { 
                serial_number = 4, 
                width = 32, 
                height = 17, 
                x = 102, 
                y = 0, 
                layer = 1, 
                is_unfold = false, 
                name = "运行", 
              }, 
              { 
                width = 32, 
                height = 17, 
                x = 134, 
                y = 0, 
                name = "退出", 
                on_click = '<function:  function: 0x027a2bacb410>', 
                layer = 1, 
                is_unfold = false, 
                serial_number = 5, 
              }, 
              count = 5, 
            }, 
            visible = true, 
            __index = '<cycle_ref:6>', 
            _layer = 2, 
            _draw_order = 2, 
            extension = { 
            }, 
            text = "title_menu", 
            gui = '<cycle_ref:1>', 
            id = "", 
            borderColor = { 
              0, 
              0, 
              0, 
              1, 
            }, 
            pressedColor = { 
              0.6, 
              1, 
              1, 
              1, 
            }, 
            type = "title_menu", 
            item_width = 100, 
          }, 
          { 
            pages = { 
              right = { 
                width = 0, 
                height = 350, 
                x = 400, 
                y = 17, 
                is_unfold = false, 
                unfold_distance = 0, 
              }, 
              bottom = { 
                width = 400, 
                height = 0, 
                x = 0, 
                y = 367, 
                is_unfold = false, 
                unfold_distance = 0, 
              }, 
              top = { 
                width = 400, 
                height = 0, 
                x = 0, 
                y = 17, 
                is_unfold = false, 
                unfold_distance = 0, 
              }, 
              left = { 
                width = 0, 
                height = 350, 
                x = 0, 
                y = 17, 
                is_unfold = false, 
                unfold_distance = 0, 
              }, 
            }, 
            height = 350, 
            x = 0, 
            y = 17, 
            parent = '<cycle_ref:4>', 
            children = { 
              { 
                width = 400, 
                height = 350, 
                _layer = 3, 
                _draw_order = 1, 
                parent = '<cycle_ref:36>', 
                children = { 
                }, 
                name = "table: 0x027a22974eb0", 
                textColor = { 
                  0, 
                  0, 
                  0, 
                  1, 
                }, 
                hoverColor = { 
                  0.8, 
                  0.8, 
                  1, 
                  1, 
                }, 
                pressedColor = { 
                  0.6, 
                  1, 
                  1, 
                  1, 
                }, 
                backgroundColor = { 
                  0.6, 
                  0.6, 
                  1, 
                  1, 
                }, 
                borderColor = { 
                  0, 
                  0, 
                  0, 
                  1, 
                }, 
                visible = true, 
                border_container_page = "main", 
                __index = '<cycle_ref:43>', 
                camera = { 
                  viewport = { 
                    width = 400, 
                    height = 350, 
                    x = 0, 
                    y = 17, 
                    centerY = 192, 
                    centerX = 200, 
                  }, 
                  scale = 1, 
                  x = 0, 
                  y = 0, 
                  virtual_screen = { 
                    y = 0, 
                    width = 800, 
                    height = 600, 
                    x = 0, 
                  }, 
                  bounds = { 
                    bottom = 175, 
                    left = -200, 
                    right = 200, 
                    top = -175, 
                  }, 
                  rotation = 0, 
                }, 
                text = "scene_2D_guiEditor", 
                gui = '<cycle_ref:1>', 
                id = "", 
                scene_gui = { 
                  tree_views = { 
                    { 
                      { 
                        width = 100, 
                        height = 30, 
                        _layer = 1, 
                        _draw_order = 1, 
                        children = { 
                        }, 
                        name = "", 
                        textColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        hoverColor = { 
                          0.8, 
                          0.8, 
                          1, 
                          1, 
                        }, 
                        pressedColor = { 
                          0.6, 
                          1, 
                          1, 
                          1, 
                        }, 
                        backgroundColor = { 
                          0.6, 
                          0.6, 
                          1, 
                          1, 
                        }, 
                        borderColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        text = "button", 
                        gui = '<cycle_ref:54>', 
                        id = "", 
                        __index = '<cycle_ref:57>', 
                        x = 67, 
                        type = "button", 
                        y = 264, 
                      }, 
                      { 
                        width = 100, 
                        height = 30, 
                        _layer = 1, 
                        _draw_order = 1, 
                        children = { 
                        }, 
                        name = "", 
                        textColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        hoverColor = { 
                          0.8, 
                          0.8, 
                          1, 
                          1, 
                        }, 
                        pressedColor = { 
                          0.6, 
                          1, 
                          1, 
                          1, 
                        }, 
                        backgroundColor = { 
                          0.6, 
                          0.6, 
                          1, 
                          1, 
                        }, 
                        borderColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        text = "button", 
                        gui = '<cycle_ref:54>', 
                        id = "", 
                        __index = '<cycle_ref:64>', 
                        x = 379, 
                        type = "button", 
                        y = 382, 
                      }, 
                      { 
                        width = 100, 
                        height = 30, 
                        _layer = 1, 
                        _draw_order = 1, 
                        children = { 
                        }, 
                        name = "", 
                        textColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        hoverColor = { 
                          0.8, 
                          0.8, 
                          1, 
                          1, 
                        }, 
                        pressedColor = { 
                          0.6, 
                          1, 
                          1, 
                          1, 
                        }, 
                        backgroundColor = { 
                          0.6, 
                          0.6, 
                          1, 
                          1, 
                        }, 
                        borderColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        text = "button", 
                        gui = '<cycle_ref:54>', 
                        id = "", 
                        __index = '<cycle_ref:71>', 
                        x = 154, 
                        type = "button", 
                        y = 256, 
                      }, 
                      { 
                        width = 100, 
                        height = 30, 
                        _layer = 1, 
                        _draw_order = 1, 
                        children = { 
                        }, 
                        name = "", 
                        textColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        hoverColor = { 
                          0.8, 
                          0.8, 
                          1, 
                          1, 
                        }, 
                        pressedColor = { 
                          0.6, 
                          1, 
                          1, 
                          1, 
                        }, 
                        backgroundColor = { 
                          0.6, 
                          0.6, 
                          1, 
                          1, 
                        }, 
                        borderColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        text = "button", 
                        gui = '<cycle_ref:54>', 
                        id = "", 
                        __index = '<cycle_ref:78>', 
                        x = 334, 
                        type = "button", 
                        y = 187, 
                      }, 
                      { 
                        width = 100, 
                        height = 30, 
                        _layer = 1, 
                        _draw_order = 1, 
                        children = { 
                        }, 
                        name = "", 
                        textColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        hoverColor = { 
                          0.8, 
                          0.8, 
                          1, 
                          1, 
                        }, 
                        pressedColor = { 
                          0.6, 
                          1, 
                          1, 
                          1, 
                        }, 
                        backgroundColor = { 
                          0.6, 
                          0.6, 
                          1, 
                          1, 
                        }, 
                        borderColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        text = "button", 
                        gui = '<cycle_ref:54>', 
                        id = "", 
                        __index = '<cycle_ref:85>', 
                        x = 31, 
                        type = "button", 
                        y = 377, 
                      }, 
                      { 
                        width = 100, 
                        height = 30, 
                        _layer = 1, 
                        _draw_order = 1, 
                        children = { 
                        }, 
                        name = "", 
                        textColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        hoverColor = { 
                          0.8, 
                          0.8, 
                          1, 
                          1, 
                        }, 
                        pressedColor = { 
                          0.6, 
                          1, 
                          1, 
                          1, 
                        }, 
                        backgroundColor = { 
                          0.6, 
                          0.6, 
                          1, 
                          1, 
                        }, 
                        borderColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        text = "button", 
                        gui = '<cycle_ref:54>', 
                        id = "", 
                        __index = '<cycle_ref:92>', 
                        x = 277, 
                        type = "button", 
                        y = 99, 
                      }, 
                      { 
                        width = 100, 
                        height = 30, 
                        _layer = 1, 
                        _draw_order = 1, 
                        children = { 
                        }, 
                        name = "", 
                        textColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        hoverColor = { 
                          0.8, 
                          0.8, 
                          1, 
                          1, 
                        }, 
                        pressedColor = { 
                          0.6, 
                          1, 
                          1, 
                          1, 
                        }, 
                        backgroundColor = { 
                          0.6, 
                          0.6, 
                          1, 
                          1, 
                        }, 
                        borderColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        text = "button", 
                        gui = '<cycle_ref:54>', 
                        id = "", 
                        __index = '<cycle_ref:99>', 
                        x = 137, 
                        type = "button", 
                        y = 206, 
                      }, 
                      { 
                        width = 100, 
                        height = 30, 
                        _layer = 1, 
                        _draw_order = 1, 
                        children = { 
                        }, 
                        name = "", 
                        textColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        hoverColor = { 
                          0.8, 
                          0.8, 
                          1, 
                          1, 
                        }, 
                        pressedColor = { 
                          0.6, 
                          1, 
                          1, 
                          1, 
                        }, 
                        backgroundColor = { 
                          0.6, 
                          0.6, 
                          1, 
                          1, 
                        }, 
                        borderColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        text = "button", 
                        gui = '<cycle_ref:54>', 
                        id = "", 
                        __index = '<cycle_ref:106>', 
                        x = 337, 
                        type = "button", 
                        y = 284, 
                      }, 
                      { 
                        width = 100, 
                        height = 30, 
                        _layer = 1, 
                        _draw_order = 1, 
                        children = { 
                        }, 
                        name = "", 
                        textColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        hoverColor = { 
                          0.8, 
                          0.8, 
                          1, 
                          1, 
                        }, 
                        pressedColor = { 
                          0.6, 
                          1, 
                          1, 
                          1, 
                        }, 
                        backgroundColor = { 
                          0.6, 
                          0.6, 
                          1, 
                          1, 
                        }, 
                        borderColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        text = "button", 
                        gui = '<cycle_ref:54>', 
                        id = "", 
                        __index = '<cycle_ref:113>', 
                        x = 185, 
                        type = "button", 
                        y = 105, 
                      }, 
                      { 
                        width = 100, 
                        height = 30, 
                        _layer = 1, 
                        _draw_order = 1, 
                        children = { 
                        }, 
                        name = "", 
                        textColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        hoverColor = { 
                          0.8, 
                          0.8, 
                          1, 
                          1, 
                        }, 
                        pressedColor = { 
                          0.6, 
                          1, 
                          1, 
                          1, 
                        }, 
                        backgroundColor = { 
                          0.6, 
                          0.6, 
                          1, 
                          1, 
                        }, 
                        borderColor = { 
                          0, 
                          0, 
                          0, 
                          1, 
                        }, 
                        text = "button", 
                        gui = '<cycle_ref:54>', 
                        id = "", 
                        __index = '<cycle_ref:120>', 
                        x = 364, 
                        type = "button", 
                        y = 21, 
                      }, 
                    }, 
                    { 
                    }, 
                    { 
                    }, 
                    { 
                    }, 
                    { 
                    }, 
                    { 
                    }, 
                    { 
                    }, 
                    { 
                    }, 
                    { 
                    }, 
                    { 
                    }, 
                    { 
                    }, 
                  }, 
                  mousemoved = '<function:  function: 0x027a20072df8>', 
                  views = { 
                    ["table: 0x027a22969420"] = '<cycle_ref:92>', 
                    ["table: 0x027a200794f0"] = '<cycle_ref:78>', 
                    ["table: 0x027a22965a38"] = '<cycle_ref:113>', 
                    ["table: 0x027a20077018"] = '<cycle_ref:64>', 
                    ["table: 0x027a2297b4a8"] = '<cycle_ref:99>', 
                    ["table: 0x027a22964930"] = '<cycle_ref:71>', 
                    ["table: 0x027a2d0f4848"] = '<cycle_ref:106>', 
                    ["table: 0x027a22973b48"] = '<cycle_ref:85>', 
                    ["table: 0x027a2d0f49e0"] = '<cycle_ref:120>', 
                    ["table: 0x027a22971ba0"] = '<cycle_ref:57>', 
                  }, 
                  input_state = { 
                    isPressed = false, 
                    pressed_views = { 
                    }, 
                    isMoved = false, 
                  }, 
                  mousereleased = '<function:  function: 0x027a2d103d50>', 
                  mousepressed = '<function:  function: 0x027a22977750>', 
                }, 
                x = 0, 
                type = "scene_2D_guiEditor", 
                y = 0, 
              }, 
            }, 
            name = "table: 0x027a20076d28", 
            textColor = { 
              0, 
              0, 
              0, 
              1, 
            }, 
            hoverColor = { 
              0.8, 
              0.8, 
              1, 
              1, 
            }, 
            pressedColor = { 
              0.6, 
              1, 
              1, 
              1, 
            }, 
            backgroundColor = { 
              1, 
              1, 
              1, 
              1, 
            }, 
            borderColor = { 
              0, 
              0, 
              0, 
              1, 
            }, 
            buttons = { 
              right = { 
                width = 17, 
                height = 35, 
                x = 383, 
                y = 174.5, 
                is_drag = false, 
                is_presses = false, 
              }, 
              bottom = { 
                width = 35, 
                height = 17, 
                x = 182.5, 
                y = 350, 
                is_drag = false, 
                is_presses = false, 
              }, 
              top = { 
                width = 35, 
                height = 17, 
                x = 182.5, 
                y = 17, 
                is_drag = false, 
                is_presses = false, 
              }, 
              left = { 
                width = 17, 
                height = 35, 
                x = 0, 
                y = 174.5, 
                is_drag = false, 
                is_presses = false, 
              }, 
            }, 
            visible = true, 
            __index = '<cycle_ref:36>', 
            _draw_order = 1, 
            text = "border_container", 
            gui = '<cycle_ref:1>', 
            id = "", 
            _layer = 2, 
            width = 400, 
            type = "border_container", 
            page_children = { 
              left = { 
              }, 
              top = { 
              }, 
              bottom = { 
              }, 
              right = { 
              }, 
              main = { 
                '<cycle_ref:43>', 
              }, 
            }, 
          }, 
        }, 
        name = "", 
        textColor = { 
          0, 
          0, 
          0, 
          1, 
        }, 
        hoverColor = { 
          0.8, 
          0.8, 
          1, 
          1, 
        }, 
        pressedColor = { 
          0.6, 
          1, 
          1, 
          1, 
        }, 
        backgroundColor = { 
          0.6, 
          0.6, 
          1, 
          1, 
        }, 
        borderColor = { 
          0, 
          0, 
          0, 
          1, 
        }, 
        __index = '<cycle_ref:4>', 
        _draw_order = 1, 
        gravity = "top|left", 
        gui = '<cycle_ref:1>', 
        id = "", 
        _layer = 1, 
        orientation = "vertical", 
        type = "line_layout", 
        text = "line_layout", 
      }, 
      { 
        isMaximized = false, 
        isMinimized = false, 
        is_title_Dragging = false, 
        dragOffsetX = 0, 
        dragOffsetY = 0, 
        __index = '<cycle_ref:161>', 
        titleBarHeight = 25, 
        titleBarColor = { 
          0.2, 
          0.4, 
          0.8, 
          1, 
        }, 
        buttons = { 
          { 
            width = 15, 
            height = 15, 
            x = 175, 
            y = 5, 
            action = '<function:  function: 0x027a2d106da8>', 
            text = "×", 
          }, 
          { 
            width = 15, 
            height = 15, 
            x = 150, 
            y = 5, 
            action = '<function:  function: 0x027a2d0f5d28>', 
            text = "□", 
          }, 
          { 
            width = 15, 
            height = 15, 
            x = 125, 
            y = 5, 
            action = '<function:  function: 0x027a2d0ee760>', 
            text = "--", 
          }, 
        }, 
        content = "window", 
        gui = '<cycle_ref:1>', 
        title = "窗口1", 
        width = 200, 
        height = 200, 
        x = 100, 
        y = 100, 
        children = { 
        }, 
        name = "", 
        textColor = { 
          1, 
          1, 
          1, 
          1, 
        }, 
        backgroundColor = { 
          0.9, 
          0.9, 
          0.9, 
          0.9, 
        }, 
        borderColor = { 
          0.1, 
          0.1, 
          0.1, 
          1, 
        }, 
        isResizable = true, 
        min_width = 75, 
        min_height = 25, 
        originalX = 100, 
        originalY = 100, 
        originalWidth = 300, 
        originalHeight = 200, 
        borderWidth = 10, 
        id = "", 
        _layer = 1, 
        visible = true, 
        type = "window", 
        _draw_order = 2, 
      }, 
    }, 
    { 
      '<cycle_ref:6>', 
      '<cycle_ref:36>', 
    }, 
    { 
      '<cycle_ref:43>', 
    }, 
    { 
    }, 
    { 
    }, 
    { 
    }, 
    { 
    }, 
    { 
    }, 
    { 
    }, 
    { 
    }, 
    { 
    }, 
  }, 
  input_state = { 
    isPressed = false, 
    pressed_views = { 
    }, 
    isMoved = false, 
  }, 
  views = { 
    ["table: 0x027a22974eb0"] = '<cycle_ref:43>', 
    ["table: 0x027a1e45f908"] = '<cycle_ref:161>', 
    ["table: 0x027a200760d0"] = '<cycle_ref:4>', 
    ["table: 0x027a2d1093d0"] = '<cycle_ref:6>', 
    ["table: 0x027a20076d28"] = '<cycle_ref:36>', 
  }, 
}